# Generated by Django 2.0.3 on 2018-03-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('artist', models.CharField(max_length=255, verbose_name='アーティスト')),
                ('price', models.IntegerField(default=0, verbose_name='値段')),
                ('genre', models.CharField(blank=True, max_length=255, verbose_name='ジャンル')),
            ],
        ),
    ]
